### ISSUE TITLE
bootstrap file looking for wrong namespace ? 

### ISSUE THREAD

**Issue by whitewhidow** [schmittjoh/JMSAopBundle#37]
Hi,

Im getting the following:
FatalErrorException in bootstrap.php.cache line 2867:
Compile Error: require(): Failed opening required '/home/xxxxx/vendor/jms/aop-bundle/JMS/AopBundle/JMSAopBundle.php' (include_path='.:/usr/share/php:/usr/share/pear')

After updating to 1.2.0

the path is actually 

    /home/xxxxx/vendor/jms/aop-bundle/JMSAopBundle.php
instead of 

    /home/xxxxx/vendor/jms/aop-bundle/JMS/AopBundle/JMSAopBundle.php

Why is the bootstrap file looking in the wrong dir?

Thx

**Comment by jancinert** [comment]
Clear php apc cache or restart php.

**Comment by whitewhidow** [comment]
yep its already fixed,   (cant remember exactly what it was, but prolly was cache yes)
