### ISSUE TITLE
Documentation: How to use @Transactional annotation.

### ISSUE THREAD

**Issue by renoirb** [schmittjoh/JMSAopBundle#5]
I am trying to use as the documentation explain and set in an entity a transaction using the @Transactional annotation.

But I cannot see how to make it work.

I am fairly new to Symfony2 and Dependency Injection and the bundle seem very powerful, but I cannot find a way around to actually use the transaction pointcut/interceptor into the project.

**Comment by mmucklo** [comment]
I think part of the confusion is over how the @DI\... tags are working, plus how annotations work in general.

To do something similar I had to create a separate Annotation class (annotated with @Annotation - see https://techpunch.co.uk/development/custom-annotations-in-symfony2-using-doctrine2s-annotation-classes except make the @Target point to "METHOD"), and then in the methodMatches look for that class with a full class name -

Example:
```php
return null !== $this->read->getMethodAnnotation($method,'SomethingBundle\Annotation\MyAnnotation');
```

Then I dropped in the services into service.yml as in the first examples and it seems to work.
